# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:01:07+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Permission(Enum):
    accountPermissionUnspecified = 'accountPermissionUnspecified'
    noAccess = 'noAccess'
    user = 'user'
    admin = 'admin'


class AccountAccess(BaseModel):
    permission: Optional[Permission] = Field(
        None,
        description='Whether the user has no access, user access, or admin access to an account. @mutable tagmanager.accounts.permissions.create @mutable tagmanager.accounts.permissions.update',
    )


class AccountFeatures(BaseModel):
    supportMultipleContainers: Optional[bool] = Field(
        None, description='Whether this Account supports multiple Containers.'
    )
    supportUserPermissions: Optional[bool] = Field(
        None,
        description='Whether this Account supports user permissions managed by GTM.',
    )


class Type(Enum):
    builtInVariableTypeUnspecified = 'builtInVariableTypeUnspecified'
    pageUrl = 'pageUrl'
    pageHostname = 'pageHostname'
    pagePath = 'pagePath'
    referrer = 'referrer'
    event = 'event'
    clickElement = 'clickElement'
    clickClasses = 'clickClasses'
    clickId = 'clickId'
    clickTarget = 'clickTarget'
    clickUrl = 'clickUrl'
    clickText = 'clickText'
    firstPartyServingUrl = 'firstPartyServingUrl'
    formElement = 'formElement'
    formClasses = 'formClasses'
    formId = 'formId'
    formTarget = 'formTarget'
    formUrl = 'formUrl'
    formText = 'formText'
    errorMessage = 'errorMessage'
    errorUrl = 'errorUrl'
    errorLine = 'errorLine'
    newHistoryUrl = 'newHistoryUrl'
    oldHistoryUrl = 'oldHistoryUrl'
    newHistoryFragment = 'newHistoryFragment'
    oldHistoryFragment = 'oldHistoryFragment'
    newHistoryState = 'newHistoryState'
    oldHistoryState = 'oldHistoryState'
    historySource = 'historySource'
    containerVersion = 'containerVersion'
    debugMode = 'debugMode'
    randomNumber = 'randomNumber'
    containerId = 'containerId'
    appId = 'appId'
    appName = 'appName'
    appVersionCode = 'appVersionCode'
    appVersionName = 'appVersionName'
    language = 'language'
    osVersion = 'osVersion'
    platform = 'platform'
    sdkVersion = 'sdkVersion'
    deviceName = 'deviceName'
    resolution = 'resolution'
    advertiserId = 'advertiserId'
    advertisingTrackingEnabled = 'advertisingTrackingEnabled'
    htmlId = 'htmlId'
    environmentName = 'environmentName'
    ampBrowserLanguage = 'ampBrowserLanguage'
    ampCanonicalPath = 'ampCanonicalPath'
    ampCanonicalUrl = 'ampCanonicalUrl'
    ampCanonicalHost = 'ampCanonicalHost'
    ampReferrer = 'ampReferrer'
    ampTitle = 'ampTitle'
    ampClientId = 'ampClientId'
    ampClientTimezone = 'ampClientTimezone'
    ampClientTimestamp = 'ampClientTimestamp'
    ampClientScreenWidth = 'ampClientScreenWidth'
    ampClientScreenHeight = 'ampClientScreenHeight'
    ampClientScrollX = 'ampClientScrollX'
    ampClientScrollY = 'ampClientScrollY'
    ampClientMaxScrollX = 'ampClientMaxScrollX'
    ampClientMaxScrollY = 'ampClientMaxScrollY'
    ampTotalEngagedTime = 'ampTotalEngagedTime'
    ampPageViewId = 'ampPageViewId'
    ampPageLoadTime = 'ampPageLoadTime'
    ampPageDownloadTime = 'ampPageDownloadTime'
    ampGtmEvent = 'ampGtmEvent'
    eventName = 'eventName'
    firebaseEventParameterCampaign = 'firebaseEventParameterCampaign'
    firebaseEventParameterCampaignAclid = 'firebaseEventParameterCampaignAclid'
    firebaseEventParameterCampaignAnid = 'firebaseEventParameterCampaignAnid'
    firebaseEventParameterCampaignClickTimestamp = (
        'firebaseEventParameterCampaignClickTimestamp'
    )
    firebaseEventParameterCampaignContent = 'firebaseEventParameterCampaignContent'
    firebaseEventParameterCampaignCp1 = 'firebaseEventParameterCampaignCp1'
    firebaseEventParameterCampaignGclid = 'firebaseEventParameterCampaignGclid'
    firebaseEventParameterCampaignSource = 'firebaseEventParameterCampaignSource'
    firebaseEventParameterCampaignTerm = 'firebaseEventParameterCampaignTerm'
    firebaseEventParameterCurrency = 'firebaseEventParameterCurrency'
    firebaseEventParameterDynamicLinkAcceptTime = (
        'firebaseEventParameterDynamicLinkAcceptTime'
    )
    firebaseEventParameterDynamicLinkLinkid = 'firebaseEventParameterDynamicLinkLinkid'
    firebaseEventParameterNotificationMessageDeviceTime = (
        'firebaseEventParameterNotificationMessageDeviceTime'
    )
    firebaseEventParameterNotificationMessageId = (
        'firebaseEventParameterNotificationMessageId'
    )
    firebaseEventParameterNotificationMessageName = (
        'firebaseEventParameterNotificationMessageName'
    )
    firebaseEventParameterNotificationMessageTime = (
        'firebaseEventParameterNotificationMessageTime'
    )
    firebaseEventParameterNotificationTopic = 'firebaseEventParameterNotificationTopic'
    firebaseEventParameterPreviousAppVersion = (
        'firebaseEventParameterPreviousAppVersion'
    )
    firebaseEventParameterPreviousOsVersion = 'firebaseEventParameterPreviousOsVersion'
    firebaseEventParameterPrice = 'firebaseEventParameterPrice'
    firebaseEventParameterProductId = 'firebaseEventParameterProductId'
    firebaseEventParameterQuantity = 'firebaseEventParameterQuantity'
    firebaseEventParameterValue = 'firebaseEventParameterValue'
    videoProvider = 'videoProvider'
    videoUrl = 'videoUrl'
    videoTitle = 'videoTitle'
    videoDuration = 'videoDuration'
    videoPercent = 'videoPercent'
    videoVisible = 'videoVisible'
    videoStatus = 'videoStatus'
    videoCurrentTime = 'videoCurrentTime'
    scrollDepthThreshold = 'scrollDepthThreshold'
    scrollDepthUnits = 'scrollDepthUnits'
    scrollDepthDirection = 'scrollDepthDirection'
    elementVisibilityRatio = 'elementVisibilityRatio'
    elementVisibilityTime = 'elementVisibilityTime'
    elementVisibilityFirstTime = 'elementVisibilityFirstTime'
    elementVisibilityRecentTime = 'elementVisibilityRecentTime'
    requestPath = 'requestPath'
    requestMethod = 'requestMethod'
    clientName = 'clientName'
    queryString = 'queryString'
    serverPageLocationUrl = 'serverPageLocationUrl'
    serverPageLocationPath = 'serverPageLocationPath'
    serverPageLocationHostname = 'serverPageLocationHostname'
    visitorRegion = 'visitorRegion'


class BuiltInVariable(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    name: Optional[str] = Field(
        None,
        description='Name of the built-in variable to be used to refer to the built-in variable.',
    )
    path: Optional[str] = Field(
        None, description="GTM BuiltInVariable's API relative path."
    )
    type: Optional[Type] = Field(
        None,
        description='Type of built-in variable. @required.tagmanager.accounts.containers.workspaces.built_in_variable.update @mutable tagmanager.accounts.containers.workspaces.built_in_variable.update',
    )
    workspaceId: Optional[str] = Field(None, description='GTM Workspace ID.')


class Type1(Enum):
    conditionTypeUnspecified = 'conditionTypeUnspecified'
    equals = 'equals'
    contains = 'contains'
    startsWith = 'startsWith'
    endsWith = 'endsWith'
    matchRegex = 'matchRegex'
    greater = 'greater'
    greaterOrEquals = 'greaterOrEquals'
    less = 'less'
    lessOrEquals = 'lessOrEquals'
    cssSelector = 'cssSelector'
    urlMatches = 'urlMatches'


class UsageContextEnum(Enum):
    usageContextUnspecified = 'usageContextUnspecified'
    web = 'web'
    android = 'android'
    ios = 'ios'
    androidSdk5 = 'androidSdk5'
    iosSdk5 = 'iosSdk5'
    amp = 'amp'
    server = 'server'


class Permission1(Enum):
    containerPermissionUnspecified = 'containerPermissionUnspecified'
    noAccess = 'noAccess'
    read = 'read'
    edit = 'edit'
    approve = 'approve'
    publish = 'publish'


class ContainerAccess(BaseModel):
    containerId: Optional[str] = Field(
        None,
        description='GTM Container ID. @mutable tagmanager.accounts.permissions.create @mutable tagmanager.accounts.permissions.update',
    )
    permission: Optional[Permission1] = Field(
        None,
        description='List of Container permissions. @mutable tagmanager.accounts.permissions.create @mutable tagmanager.accounts.permissions.update',
    )


class ContainerFeatures(BaseModel):
    supportBuiltInVariables: Optional[bool] = Field(
        None, description='Whether this Container supports built-in variables'
    )
    supportClients: Optional[bool] = Field(
        None, description='Whether this Container supports clients.'
    )
    supportEnvironments: Optional[bool] = Field(
        None, description='Whether this Container supports environments.'
    )
    supportFolders: Optional[bool] = Field(
        None, description='Whether this Container supports folders.'
    )
    supportGtagConfigs: Optional[bool] = Field(
        None, description='Whether this Container supports Google tag config.'
    )
    supportTags: Optional[bool] = Field(
        None, description='Whether this Container supports tags.'
    )
    supportTemplates: Optional[bool] = Field(
        None, description='Whether this Container supports templates.'
    )
    supportTriggers: Optional[bool] = Field(
        None, description='Whether this Container supports triggers.'
    )
    supportUserPermissions: Optional[bool] = Field(
        None,
        description='Whether this Container supports user permissions managed by GTM.',
    )
    supportVariables: Optional[bool] = Field(
        None, description='Whether this Container supports variables.'
    )
    supportVersions: Optional[bool] = Field(
        None, description='Whether this Container supports Container versions.'
    )
    supportWorkspaces: Optional[bool] = Field(
        None, description='Whether this Container supports workspaces.'
    )
    supportZones: Optional[bool] = Field(
        None, description='Whether this Container supports zones.'
    )


class ContainerVersionHeader(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    containerVersionId: Optional[str] = Field(
        None,
        description='The Container Version ID uniquely identifies the GTM Container Version.',
    )
    deleted: Optional[bool] = Field(
        None,
        description='A value of true indicates this container version has been deleted.',
    )
    name: Optional[str] = Field(None, description='Container version display name.')
    numClients: Optional[str] = Field(
        None, description='Number of clients in the container version.'
    )
    numCustomTemplates: Optional[str] = Field(
        None, description='Number of custom templates in the container version.'
    )
    numGtagConfigs: Optional[str] = Field(
        None, description='Number of Google tag configs in the container version.'
    )
    numMacros: Optional[str] = Field(
        None, description='Number of macros in the container version.'
    )
    numRules: Optional[str] = Field(
        None, description='Number of rules in the container version.'
    )
    numTags: Optional[str] = Field(
        None, description='Number of tags in the container version.'
    )
    numTransformations: Optional[str] = Field(
        None, description='Number of transformations in the container version.'
    )
    numTriggers: Optional[str] = Field(
        None, description='Number of triggers in the container version.'
    )
    numVariables: Optional[str] = Field(
        None, description='Number of variables in the container version.'
    )
    numZones: Optional[str] = Field(
        None, description='Number of zones in the container version.'
    )
    path: Optional[str] = Field(
        None, description="GTM Container Version's API relative path."
    )


class CreateBuiltInVariableResponse(BaseModel):
    builtInVariable: Optional[List[BuiltInVariable]] = Field(
        None, description='List of created built-in variables.'
    )


class CreateContainerVersionRequestVersionOptions(BaseModel):
    name: Optional[str] = Field(
        None, description='The name of the container version to be created.'
    )
    notes: Optional[str] = Field(
        None, description='The notes of the container version to be created.'
    )


class Destination(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    destinationId: Optional[str] = Field(None, description='Destination ID.')
    destinationLinkId: Optional[str] = Field(
        None, description='The Destination link ID uniquely identifies the Destination.'
    )
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the Google Tag Destination as computed at storage time. This value is recomputed whenever the destination is modified.',
    )
    name: Optional[str] = Field(None, description='Destination display name.')
    path: Optional[str] = Field(None, description="Destination's API relative path.")
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI.'
    )


class ChangeStatus(Enum):
    changeStatusUnspecified = 'changeStatusUnspecified'
    none = 'none'
    added = 'added'
    deleted = 'deleted'
    updated = 'updated'


class Type2(Enum):
    user = 'user'
    live = 'live'
    latest = 'latest'
    workspace = 'workspace'


class Environment(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    authorizationCode: Optional[str] = Field(
        None, description='The environment authorization code.'
    )
    authorizationTimestamp: Optional[str] = Field(
        None, description='The last update time-stamp for the authorization code.'
    )
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    containerVersionId: Optional[str] = Field(
        None, description='Represents a link to a container version.'
    )
    description: Optional[str] = Field(
        None,
        description='The environment description. Can be set or changed only on USER type environments. @mutable tagmanager.accounts.containers.environments.create @mutable tagmanager.accounts.containers.environments.update',
    )
    enableDebug: Optional[bool] = Field(
        None,
        description='Whether or not to enable debug by default for the environment. @mutable tagmanager.accounts.containers.environments.create @mutable tagmanager.accounts.containers.environments.update',
    )
    environmentId: Optional[str] = Field(
        None, description='GTM Environment ID uniquely identifies the GTM Environment.'
    )
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM environment as computed at storage time. This value is recomputed whenever the environment is modified.',
    )
    name: Optional[str] = Field(
        None,
        description='The environment display name. Can be set or changed only on USER type environments. @mutable tagmanager.accounts.containers.environments.create @mutable tagmanager.accounts.containers.environments.update',
    )
    path: Optional[str] = Field(
        None, description="GTM Environment's API relative path."
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    type: Optional[Type2] = Field(None, description='The type of this environment.')
    url: Optional[str] = Field(
        None,
        description='Default preview page url for the environment. @mutable tagmanager.accounts.containers.environments.create @mutable tagmanager.accounts.containers.environments.update',
    )
    workspaceId: Optional[str] = Field(
        None, description='Represents a link to a quick preview of a workspace.'
    )


class Folder(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Folder as computed at storage time. This value is recomputed whenever the folder is modified.',
    )
    folderId: Optional[str] = Field(
        None, description='The Folder ID uniquely identifies the GTM Folder.'
    )
    name: Optional[str] = Field(
        None,
        description='Folder display name. @mutable tagmanager.accounts.containers.workspaces.folders.create @mutable tagmanager.accounts.containers.workspaces.folders.update',
    )
    notes: Optional[str] = Field(
        None,
        description='User notes on how to apply this folder in the container. @mutable tagmanager.accounts.containers.workspaces.folders.create @mutable tagmanager.accounts.containers.workspaces.folders.update',
    )
    path: Optional[str] = Field(None, description="GTM Folder's API relative path.")
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    workspaceId: Optional[str] = Field(None, description='GTM Workspace ID.')


class GalleryReference(BaseModel):
    host: Optional[str] = Field(
        None, description='The name of the host for the community gallery template.'
    )
    isModified: Optional[bool] = Field(
        None,
        description='If a user has manually edited the community gallery template.',
    )
    owner: Optional[str] = Field(
        None, description='The name of the owner for the community gallery template.'
    )
    repository: Optional[str] = Field(
        None,
        description='The name of the repository for the community gallery template.',
    )
    signature: Optional[str] = Field(
        None,
        description='The signature of the community gallery template as computed at import time. This value is recomputed whenever the template is updated from the gallery.',
    )
    version: Optional[str] = Field(
        None, description='The version of the community gallery template.'
    )


class GetContainerSnippetResponse(BaseModel):
    snippet: Optional[str] = Field(None, description='Tagging snippet for a Container.')


class ListContainerVersionsResponse(BaseModel):
    containerVersionHeader: Optional[List[ContainerVersionHeader]] = Field(
        None, description='All container version headers of a GTM Container.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListDestinationsResponse(BaseModel):
    destination: Optional[List[Destination]] = Field(
        None, description='All Destinations linked to a GTM Container.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListEnabledBuiltInVariablesResponse(BaseModel):
    builtInVariable: Optional[List[BuiltInVariable]] = Field(
        None, description='All GTM BuiltInVariables of a GTM container.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListEnvironmentsResponse(BaseModel):
    environment: Optional[List[Environment]] = Field(
        None, description='All Environments of a GTM Container.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListFoldersResponse(BaseModel):
    folder: Optional[List[Folder]] = Field(
        None, description='All GTM Folders of a GTM Container.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class Type3(Enum):
    typeUnspecified = 'typeUnspecified'
    template = 'template'
    integer = 'integer'
    boolean = 'boolean'
    list = 'list'
    map = 'map'
    triggerReference = 'triggerReference'
    tagReference = 'tagReference'


class Parameter(BaseModel):
    key: Optional[str] = Field(
        None,
        description='The named key that uniquely identifies a parameter. Required for top-level parameters, as well as map values. Ignored for list values. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    list: Optional[List[Parameter]] = Field(
        None,
        description="This list parameter's parameters (keys will be ignored). @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update",
    )
    map: Optional[List[Parameter]] = Field(
        None,
        description="This map parameter's parameters (must have keys; keys must be unique). @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update",
    )
    type: Optional[Type3] = Field(
        None,
        description="The parameter type. Valid values are: - boolean: The value represents a boolean, represented as 'true' or 'false' - integer: The value represents a 64-bit signed integer value, in base 10 - list: A list of parameters should be specified - map: A map of parameters should be specified - template: The value represents any text; this can include variable references (even variable references that might return non-string types) - trigger_reference: The value represents a trigger, represented as the trigger id - tag_reference: The value represents a tag, represented as the tag name @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update",
    )
    value: Optional[str] = Field(
        None,
        description='A parameter\'s value (may contain variable references such as "{{myVariable}}") as appropriate to the specified type. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )


class RevertBuiltInVariableResponse(BaseModel):
    enabled: Optional[bool] = Field(
        None, description='Whether the built-in variable is enabled after reversion.'
    )


class RevertFolderResponse(BaseModel):
    folder: Optional[Folder] = Field(
        None,
        description='Folder as it appears in the latest container version since the last workspace synchronization operation. If no folder is present, that means the folder was deleted in the latest container version.',
    )


class SetupTag(BaseModel):
    stopOnSetupFailure: Optional[bool] = Field(
        None,
        description='If true, fire the main tag if and only if the setup tag fires successfully. If false, fire the main tag regardless of setup tag firing status.',
    )
    tagName: Optional[str] = Field(None, description='The name of the setup tag.')


class SyncStatus(BaseModel):
    mergeConflict: Optional[bool] = Field(
        None, description='Synchornization operation detected a merge conflict.'
    )
    syncError: Optional[bool] = Field(
        None, description='An error occurred during the synchronization operation.'
    )


class TagFiringOption(Enum):
    tagFiringOptionUnspecified = 'tagFiringOptionUnspecified'
    unlimited = 'unlimited'
    oncePerEvent = 'oncePerEvent'
    oncePerLoad = 'oncePerLoad'


class ConsentStatus(Enum):
    notSet = 'notSet'
    notNeeded = 'notNeeded'
    needed = 'needed'


class TagConsentSetting(BaseModel):
    consentStatus: Optional[ConsentStatus] = Field(
        None,
        description="The tag's consent status. If set to NEEDED, the runtime will check that the consent types specified by the consent_type field have been granted.",
    )
    consentType: Optional[Parameter] = Field(
        None,
        description='The type of consents to check for during tag firing if in the consent NEEDED state. This parameter must be of type LIST where each list item is of type STRING.',
    )


class TeardownTag(BaseModel):
    stopTeardownOnFailure: Optional[bool] = Field(
        None,
        description='If true, fire the teardown tag if and only if the main tag fires successfully. If false, fire the teardown tag regardless of main tag firing status.',
    )
    tagName: Optional[str] = Field(None, description='The name of the teardown tag.')


class Type4(Enum):
    eventTypeUnspecified = 'eventTypeUnspecified'
    pageview = 'pageview'
    domReady = 'domReady'
    windowLoaded = 'windowLoaded'
    customEvent = 'customEvent'
    triggerGroup = 'triggerGroup'
    init = 'init'
    consentInit = 'consentInit'
    serverPageview = 'serverPageview'
    always = 'always'
    firebaseAppException = 'firebaseAppException'
    firebaseAppUpdate = 'firebaseAppUpdate'
    firebaseCampaign = 'firebaseCampaign'
    firebaseFirstOpen = 'firebaseFirstOpen'
    firebaseInAppPurchase = 'firebaseInAppPurchase'
    firebaseNotificationDismiss = 'firebaseNotificationDismiss'
    firebaseNotificationForeground = 'firebaseNotificationForeground'
    firebaseNotificationOpen = 'firebaseNotificationOpen'
    firebaseNotificationReceive = 'firebaseNotificationReceive'
    firebaseOsUpdate = 'firebaseOsUpdate'
    firebaseSessionStart = 'firebaseSessionStart'
    firebaseUserEngagement = 'firebaseUserEngagement'
    formSubmission = 'formSubmission'
    click = 'click'
    linkClick = 'linkClick'
    jsError = 'jsError'
    historyChange = 'historyChange'
    timer = 'timer'
    ampClick = 'ampClick'
    ampTimer = 'ampTimer'
    ampScroll = 'ampScroll'
    ampVisibility = 'ampVisibility'
    youTubeVideo = 'youTubeVideo'
    scrollDepth = 'scrollDepth'
    elementVisibility = 'elementVisibility'


class UserPermission(BaseModel):
    accountAccess: Optional[AccountAccess] = Field(
        None,
        description='GTM Account access permissions. @mutable tagmanager.accounts.permissions.create @mutable tagmanager.accounts.permissions.update',
    )
    accountId: Optional[str] = Field(
        None, description='The Account ID uniquely identifies the GTM Account.'
    )
    containerAccess: Optional[List[ContainerAccess]] = Field(
        None,
        description='GTM Container access permissions. @mutable tagmanager.accounts.permissions.create @mutable tagmanager.accounts.permissions.update',
    )
    emailAddress: Optional[str] = Field(
        None,
        description="User's email address. @mutable tagmanager.accounts.permissions.create",
    )
    path: Optional[str] = Field(
        None, description="GTM UserPermission's API relative path."
    )


class CaseConversionType(Enum):
    none = 'none'
    lowercase = 'lowercase'
    uppercase = 'uppercase'


class VariableFormatValue(BaseModel):
    caseConversionType: Optional[CaseConversionType] = Field(
        None,
        description='The option to convert a string-type variable value to either lowercase or uppercase.',
    )
    convertFalseToValue: Optional[Parameter] = Field(
        None, description='The value to convert if a variable value is false.'
    )
    convertNullToValue: Optional[Parameter] = Field(
        None, description='The value to convert if a variable value is null.'
    )
    convertTrueToValue: Optional[Parameter] = Field(
        None, description='The value to convert if a variable value is true.'
    )
    convertUndefinedToValue: Optional[Parameter] = Field(
        None, description='The value to convert if a variable value is undefined.'
    )


class Workspace(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    description: Optional[str] = Field(
        None,
        description='Workspace description. @mutable tagmanager.accounts.containers.workspaces.create @mutable tagmanager.accounts.containers.workspaces.update',
    )
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Workspace as computed at storage time. This value is recomputed whenever the workspace is modified.',
    )
    name: Optional[str] = Field(
        None,
        description='Workspace display name. @mutable tagmanager.accounts.containers.workspaces.create @mutable tagmanager.accounts.containers.workspaces.update',
    )
    path: Optional[str] = Field(None, description="GTM Workspace's API relative path.")
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    workspaceId: Optional[str] = Field(
        None, description='The Workspace ID uniquely identifies the GTM Workspace.'
    )


class ZoneChildContainer(BaseModel):
    nickname: Optional[str] = Field(
        None, description="The zone's nickname for the child container."
    )
    publicId: Optional[str] = Field(
        None, description="The child container's public id."
    )


class ZoneTypeRestriction(BaseModel):
    enable: Optional[bool] = Field(
        None, description='True if type restrictions have been enabled for this Zone.'
    )
    whitelistedTypeId: Optional[List[str]] = Field(
        None,
        description='List of type public ids that have been whitelisted for use in this Zone.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class TypeEnum(Enum):
    builtInVariableTypeUnspecified = 'builtInVariableTypeUnspecified'
    pageUrl = 'pageUrl'
    pageHostname = 'pageHostname'
    pagePath = 'pagePath'
    referrer = 'referrer'
    event = 'event'
    clickElement = 'clickElement'
    clickClasses = 'clickClasses'
    clickId = 'clickId'
    clickTarget = 'clickTarget'
    clickUrl = 'clickUrl'
    clickText = 'clickText'
    firstPartyServingUrl = 'firstPartyServingUrl'
    formElement = 'formElement'
    formClasses = 'formClasses'
    formId = 'formId'
    formTarget = 'formTarget'
    formUrl = 'formUrl'
    formText = 'formText'
    errorMessage = 'errorMessage'
    errorUrl = 'errorUrl'
    errorLine = 'errorLine'
    newHistoryUrl = 'newHistoryUrl'
    oldHistoryUrl = 'oldHistoryUrl'
    newHistoryFragment = 'newHistoryFragment'
    oldHistoryFragment = 'oldHistoryFragment'
    newHistoryState = 'newHistoryState'
    oldHistoryState = 'oldHistoryState'
    historySource = 'historySource'
    containerVersion = 'containerVersion'
    debugMode = 'debugMode'
    randomNumber = 'randomNumber'
    containerId = 'containerId'
    appId = 'appId'
    appName = 'appName'
    appVersionCode = 'appVersionCode'
    appVersionName = 'appVersionName'
    language = 'language'
    osVersion = 'osVersion'
    platform = 'platform'
    sdkVersion = 'sdkVersion'
    deviceName = 'deviceName'
    resolution = 'resolution'
    advertiserId = 'advertiserId'
    advertisingTrackingEnabled = 'advertisingTrackingEnabled'
    htmlId = 'htmlId'
    environmentName = 'environmentName'
    ampBrowserLanguage = 'ampBrowserLanguage'
    ampCanonicalPath = 'ampCanonicalPath'
    ampCanonicalUrl = 'ampCanonicalUrl'
    ampCanonicalHost = 'ampCanonicalHost'
    ampReferrer = 'ampReferrer'
    ampTitle = 'ampTitle'
    ampClientId = 'ampClientId'
    ampClientTimezone = 'ampClientTimezone'
    ampClientTimestamp = 'ampClientTimestamp'
    ampClientScreenWidth = 'ampClientScreenWidth'
    ampClientScreenHeight = 'ampClientScreenHeight'
    ampClientScrollX = 'ampClientScrollX'
    ampClientScrollY = 'ampClientScrollY'
    ampClientMaxScrollX = 'ampClientMaxScrollX'
    ampClientMaxScrollY = 'ampClientMaxScrollY'
    ampTotalEngagedTime = 'ampTotalEngagedTime'
    ampPageViewId = 'ampPageViewId'
    ampPageLoadTime = 'ampPageLoadTime'
    ampPageDownloadTime = 'ampPageDownloadTime'
    ampGtmEvent = 'ampGtmEvent'
    eventName = 'eventName'
    firebaseEventParameterCampaign = 'firebaseEventParameterCampaign'
    firebaseEventParameterCampaignAclid = 'firebaseEventParameterCampaignAclid'
    firebaseEventParameterCampaignAnid = 'firebaseEventParameterCampaignAnid'
    firebaseEventParameterCampaignClickTimestamp = (
        'firebaseEventParameterCampaignClickTimestamp'
    )
    firebaseEventParameterCampaignContent = 'firebaseEventParameterCampaignContent'
    firebaseEventParameterCampaignCp1 = 'firebaseEventParameterCampaignCp1'
    firebaseEventParameterCampaignGclid = 'firebaseEventParameterCampaignGclid'
    firebaseEventParameterCampaignSource = 'firebaseEventParameterCampaignSource'
    firebaseEventParameterCampaignTerm = 'firebaseEventParameterCampaignTerm'
    firebaseEventParameterCurrency = 'firebaseEventParameterCurrency'
    firebaseEventParameterDynamicLinkAcceptTime = (
        'firebaseEventParameterDynamicLinkAcceptTime'
    )
    firebaseEventParameterDynamicLinkLinkid = 'firebaseEventParameterDynamicLinkLinkid'
    firebaseEventParameterNotificationMessageDeviceTime = (
        'firebaseEventParameterNotificationMessageDeviceTime'
    )
    firebaseEventParameterNotificationMessageId = (
        'firebaseEventParameterNotificationMessageId'
    )
    firebaseEventParameterNotificationMessageName = (
        'firebaseEventParameterNotificationMessageName'
    )
    firebaseEventParameterNotificationMessageTime = (
        'firebaseEventParameterNotificationMessageTime'
    )
    firebaseEventParameterNotificationTopic = 'firebaseEventParameterNotificationTopic'
    firebaseEventParameterPreviousAppVersion = (
        'firebaseEventParameterPreviousAppVersion'
    )
    firebaseEventParameterPreviousOsVersion = 'firebaseEventParameterPreviousOsVersion'
    firebaseEventParameterPrice = 'firebaseEventParameterPrice'
    firebaseEventParameterProductId = 'firebaseEventParameterProductId'
    firebaseEventParameterQuantity = 'firebaseEventParameterQuantity'
    firebaseEventParameterValue = 'firebaseEventParameterValue'
    videoProvider = 'videoProvider'
    videoUrl = 'videoUrl'
    videoTitle = 'videoTitle'
    videoDuration = 'videoDuration'
    videoPercent = 'videoPercent'
    videoVisible = 'videoVisible'
    videoStatus = 'videoStatus'
    videoCurrentTime = 'videoCurrentTime'
    scrollDepthThreshold = 'scrollDepthThreshold'
    scrollDepthUnits = 'scrollDepthUnits'
    scrollDepthDirection = 'scrollDepthDirection'
    elementVisibilityRatio = 'elementVisibilityRatio'
    elementVisibilityTime = 'elementVisibilityTime'
    elementVisibilityFirstTime = 'elementVisibilityFirstTime'
    elementVisibilityRecentTime = 'elementVisibilityRecentTime'
    requestPath = 'requestPath'
    requestMethod = 'requestMethod'
    clientName = 'clientName'
    queryString = 'queryString'
    serverPageLocationUrl = 'serverPageLocationUrl'
    serverPageLocationPath = 'serverPageLocationPath'
    serverPageLocationHostname = 'serverPageLocationHostname'
    visitorRegion = 'visitorRegion'


class Type5(RootModel[List[TypeEnum]]):
    root: List[TypeEnum]


class Type6(RootModel[List[TypeEnum]]):
    root: List[TypeEnum]


class Type7(Enum):
    builtInVariableTypeUnspecified = 'builtInVariableTypeUnspecified'
    pageUrl = 'pageUrl'
    pageHostname = 'pageHostname'
    pagePath = 'pagePath'
    referrer = 'referrer'
    event = 'event'
    clickElement = 'clickElement'
    clickClasses = 'clickClasses'
    clickId = 'clickId'
    clickTarget = 'clickTarget'
    clickUrl = 'clickUrl'
    clickText = 'clickText'
    firstPartyServingUrl = 'firstPartyServingUrl'
    formElement = 'formElement'
    formClasses = 'formClasses'
    formId = 'formId'
    formTarget = 'formTarget'
    formUrl = 'formUrl'
    formText = 'formText'
    errorMessage = 'errorMessage'
    errorUrl = 'errorUrl'
    errorLine = 'errorLine'
    newHistoryUrl = 'newHistoryUrl'
    oldHistoryUrl = 'oldHistoryUrl'
    newHistoryFragment = 'newHistoryFragment'
    oldHistoryFragment = 'oldHistoryFragment'
    newHistoryState = 'newHistoryState'
    oldHistoryState = 'oldHistoryState'
    historySource = 'historySource'
    containerVersion = 'containerVersion'
    debugMode = 'debugMode'
    randomNumber = 'randomNumber'
    containerId = 'containerId'
    appId = 'appId'
    appName = 'appName'
    appVersionCode = 'appVersionCode'
    appVersionName = 'appVersionName'
    language = 'language'
    osVersion = 'osVersion'
    platform = 'platform'
    sdkVersion = 'sdkVersion'
    deviceName = 'deviceName'
    resolution = 'resolution'
    advertiserId = 'advertiserId'
    advertisingTrackingEnabled = 'advertisingTrackingEnabled'
    htmlId = 'htmlId'
    environmentName = 'environmentName'
    ampBrowserLanguage = 'ampBrowserLanguage'
    ampCanonicalPath = 'ampCanonicalPath'
    ampCanonicalUrl = 'ampCanonicalUrl'
    ampCanonicalHost = 'ampCanonicalHost'
    ampReferrer = 'ampReferrer'
    ampTitle = 'ampTitle'
    ampClientId = 'ampClientId'
    ampClientTimezone = 'ampClientTimezone'
    ampClientTimestamp = 'ampClientTimestamp'
    ampClientScreenWidth = 'ampClientScreenWidth'
    ampClientScreenHeight = 'ampClientScreenHeight'
    ampClientScrollX = 'ampClientScrollX'
    ampClientScrollY = 'ampClientScrollY'
    ampClientMaxScrollX = 'ampClientMaxScrollX'
    ampClientMaxScrollY = 'ampClientMaxScrollY'
    ampTotalEngagedTime = 'ampTotalEngagedTime'
    ampPageViewId = 'ampPageViewId'
    ampPageLoadTime = 'ampPageLoadTime'
    ampPageDownloadTime = 'ampPageDownloadTime'
    ampGtmEvent = 'ampGtmEvent'
    eventName = 'eventName'
    firebaseEventParameterCampaign = 'firebaseEventParameterCampaign'
    firebaseEventParameterCampaignAclid = 'firebaseEventParameterCampaignAclid'
    firebaseEventParameterCampaignAnid = 'firebaseEventParameterCampaignAnid'
    firebaseEventParameterCampaignClickTimestamp = (
        'firebaseEventParameterCampaignClickTimestamp'
    )
    firebaseEventParameterCampaignContent = 'firebaseEventParameterCampaignContent'
    firebaseEventParameterCampaignCp1 = 'firebaseEventParameterCampaignCp1'
    firebaseEventParameterCampaignGclid = 'firebaseEventParameterCampaignGclid'
    firebaseEventParameterCampaignSource = 'firebaseEventParameterCampaignSource'
    firebaseEventParameterCampaignTerm = 'firebaseEventParameterCampaignTerm'
    firebaseEventParameterCurrency = 'firebaseEventParameterCurrency'
    firebaseEventParameterDynamicLinkAcceptTime = (
        'firebaseEventParameterDynamicLinkAcceptTime'
    )
    firebaseEventParameterDynamicLinkLinkid = 'firebaseEventParameterDynamicLinkLinkid'
    firebaseEventParameterNotificationMessageDeviceTime = (
        'firebaseEventParameterNotificationMessageDeviceTime'
    )
    firebaseEventParameterNotificationMessageId = (
        'firebaseEventParameterNotificationMessageId'
    )
    firebaseEventParameterNotificationMessageName = (
        'firebaseEventParameterNotificationMessageName'
    )
    firebaseEventParameterNotificationMessageTime = (
        'firebaseEventParameterNotificationMessageTime'
    )
    firebaseEventParameterNotificationTopic = 'firebaseEventParameterNotificationTopic'
    firebaseEventParameterPreviousAppVersion = (
        'firebaseEventParameterPreviousAppVersion'
    )
    firebaseEventParameterPreviousOsVersion = 'firebaseEventParameterPreviousOsVersion'
    firebaseEventParameterPrice = 'firebaseEventParameterPrice'
    firebaseEventParameterProductId = 'firebaseEventParameterProductId'
    firebaseEventParameterQuantity = 'firebaseEventParameterQuantity'
    firebaseEventParameterValue = 'firebaseEventParameterValue'
    videoProvider = 'videoProvider'
    videoUrl = 'videoUrl'
    videoTitle = 'videoTitle'
    videoDuration = 'videoDuration'
    videoPercent = 'videoPercent'
    videoVisible = 'videoVisible'
    videoStatus = 'videoStatus'
    videoCurrentTime = 'videoCurrentTime'
    scrollDepthThreshold = 'scrollDepthThreshold'
    scrollDepthUnits = 'scrollDepthUnits'
    scrollDepthDirection = 'scrollDepthDirection'
    elementVisibilityRatio = 'elementVisibilityRatio'
    elementVisibilityTime = 'elementVisibilityTime'
    elementVisibilityFirstTime = 'elementVisibilityFirstTime'
    elementVisibilityRecentTime = 'elementVisibilityRecentTime'
    requestPath = 'requestPath'
    requestMethod = 'requestMethod'
    clientName = 'clientName'
    queryString = 'queryString'
    serverPageLocationUrl = 'serverPageLocationUrl'
    serverPageLocationPath = 'serverPageLocationPath'
    serverPageLocationHostname = 'serverPageLocationHostname'
    visitorRegion = 'visitorRegion'


class SettingSource(Enum):
    settingSourceUnspecified = 'settingSourceUnspecified'
    current = 'current'
    other = 'other'


class TagId(RootModel[List[str]]):
    root: List[str]


class TriggerId(RootModel[List[str]]):
    root: List[str]


class VariableId(RootModel[List[str]]):
    root: List[str]


class Account(BaseModel):
    accountId: Optional[str] = Field(
        None, description='The Account ID uniquely identifies the GTM Account.'
    )
    features: Optional[AccountFeatures] = Field(
        None, description='Read-only Account feature set'
    )
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Account as computed at storage time. This value is recomputed whenever the account is modified.',
    )
    name: Optional[str] = Field(
        None,
        description='Account display name. @mutable tagmanager.accounts.create @mutable tagmanager.accounts.update',
    )
    path: Optional[str] = Field(None, description="GTM Account's API relative path.")
    shareData: Optional[bool] = Field(
        None,
        description='Whether the account shares data anonymously with Google and others. This flag enables benchmarking by sharing your data in an anonymous form. Google will remove all identifiable information about your website, combine the data with hundreds of other anonymous sites and report aggregate trends in the benchmarking service. @mutable tagmanager.accounts.create @mutable tagmanager.accounts.update',
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )


class Client(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    clientId: Optional[str] = Field(
        None, description='The Client ID uniquely identifies the GTM client.'
    )
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Client as computed at storage time. This value is recomputed whenever the client is modified.',
    )
    name: Optional[str] = Field(
        None,
        description='Client display name. @mutable tagmanager.accounts.containers.workspaces.clients.create @mutable tagmanager.accounts.containers.workspaces.clients.update',
    )
    notes: Optional[str] = Field(
        None,
        description='User notes on how to apply this tag in the container. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    parameter: Optional[List[Parameter]] = Field(
        None,
        description="The client's parameters. @mutable tagmanager.accounts.containers.workspaces.clients.create @mutable tagmanager.accounts.containers.workspaces.clients.update",
    )
    parentFolderId: Optional[str] = Field(None, description='Parent folder id.')
    path: Optional[str] = Field(None, description="GTM client's API relative path.")
    priority: Optional[int] = Field(
        None,
        description='Priority determines relative firing order. @mutable tagmanager.accounts.containers.workspaces.clients.create @mutable tagmanager.accounts.containers.workspaces.clients.update',
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    type: Optional[str] = Field(
        None,
        description='Client type. @mutable tagmanager.accounts.containers.workspaces.clients.create @mutable tagmanager.accounts.containers.workspaces.clients.update',
    )
    workspaceId: Optional[str] = Field(None, description='GTM Workspace ID.')


class Condition(BaseModel):
    parameter: Optional[List[Parameter]] = Field(
        None,
        description="A list of named parameters (key/value), depending on the condition's type. Notes: - For binary operators, include parameters named arg0 and arg1 for specifying the left and right operands, respectively. - At this time, the left operand (arg0) must be a reference to a variable. - For case-insensitive Regex matching, include a boolean parameter named ignore_case that is set to true. If not specified or set to any other value, the matching will be case sensitive. - To negate an operator, include a boolean parameter named negate boolean parameter that is set to true. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update",
    )
    type: Optional[Type1] = Field(
        None,
        description='The type of operator for this condition. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )


class Container(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    containerId: Optional[str] = Field(
        None, description='The Container ID uniquely identifies the GTM Container.'
    )
    domainName: Optional[List[str]] = Field(
        None,
        description='List of domain names associated with the Container. @mutable tagmanager.accounts.containers.create @mutable tagmanager.accounts.containers.update',
    )
    features: Optional[ContainerFeatures] = Field(
        None, description='Read-only Container feature set.'
    )
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Container as computed at storage time. This value is recomputed whenever the account is modified.',
    )
    name: Optional[str] = Field(
        None,
        description='Container display name. @mutable tagmanager.accounts.containers.create @mutable tagmanager.accounts.containers.update',
    )
    notes: Optional[str] = Field(
        None,
        description='Container Notes. @mutable tagmanager.accounts.containers.create @mutable tagmanager.accounts.containers.update',
    )
    path: Optional[str] = Field(None, description="GTM Container's API relative path.")
    publicId: Optional[str] = Field(None, description='Container Public ID.')
    tagIds: Optional[List[str]] = Field(
        None, description='All Tag IDs that refer to this Container.'
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    taggingServerUrls: Optional[List[str]] = Field(
        None,
        description='List of server-side container URLs for the Container. If multiple URLs are provided, all URL paths must match. @mutable tagmanager.accounts.containers.create @mutable tagmanager.accounts.containers.update',
    )
    usageContext: Optional[List[UsageContextEnum]] = Field(
        None,
        description='List of Usage Contexts for the Container. Valid values include: web, android, or ios. @mutable tagmanager.accounts.containers.create @mutable tagmanager.accounts.containers.update',
    )


class CustomTemplate(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Custom Template as computed at storage time. This value is recomputed whenever the template is modified.',
    )
    galleryReference: Optional[GalleryReference] = Field(
        None, description='A reference to the Community Template Gallery entry.'
    )
    name: Optional[str] = Field(None, description='Custom Template display name.')
    path: Optional[str] = Field(
        None, description="GTM Custom Template's API relative path."
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    templateData: Optional[str] = Field(
        None, description='The custom template in text format.'
    )
    templateId: Optional[str] = Field(
        None,
        description='The Custom Template ID uniquely identifies the GTM custom template.',
    )
    workspaceId: Optional[str] = Field(None, description='GTM Workspace ID.')


class GtagConfig(BaseModel):
    accountId: Optional[str] = Field(None, description='Google tag account ID.')
    containerId: Optional[str] = Field(None, description='Google tag container ID.')
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the Google tag config as computed at storage time. This value is recomputed whenever the config is modified.',
    )
    gtagConfigId: Optional[str] = Field(
        None, description='The ID uniquely identifies the Google tag config.'
    )
    parameter: Optional[List[Parameter]] = Field(
        None,
        description="The Google tag config's parameters. @mutable tagmanager.accounts.containers.workspaces.gtag_config.create @mutable tagmanager.accounts.containers.workspaces.gtag_config.update",
    )
    path: Optional[str] = Field(
        None, description="Google tag config's API relative path."
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    type: Optional[str] = Field(
        None,
        description='Google tag config type. @required tagmanager.accounts.containers.workspaces.gtag_config.create @required tagmanager.accounts.containers.workspaces.gtag_config.update @mutable tagmanager.accounts.containers.workspaces.gtag_config.create @mutable tagmanager.accounts.containers.workspaces.gtag_config.update',
    )
    workspaceId: Optional[str] = Field(
        None,
        description='Google tag workspace ID. Only used by GTM containers. Set to 0 otherwise.',
    )


class ListAccountsResponse(BaseModel):
    account: Optional[List[Account]] = Field(
        None, description='List of GTM Accounts that a user has access to.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListClientsResponse(BaseModel):
    client: Optional[List[Client]] = Field(
        None, description='All GTM Clients of a GTM Container.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListContainersResponse(BaseModel):
    container: Optional[List[Container]] = Field(
        None, description='All Containers of a GTM Account.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListGtagConfigResponse(BaseModel):
    gtagConfig: Optional[List[GtagConfig]] = Field(
        None, description='All Google tag configs in a Container.'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )


class ListTemplatesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    template: Optional[List[CustomTemplate]] = Field(
        None, description='All GTM Custom Templates of a GTM Container.'
    )


class ListUserPermissionsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    userPermission: Optional[List[UserPermission]] = Field(
        None, description='All GTM UserPermissions of a GTM Account.'
    )


class ListWorkspacesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    workspace: Optional[List[Workspace]] = Field(
        None, description='All Workspaces of a GTM Container.'
    )


class RevertClientResponse(BaseModel):
    client: Optional[Client] = Field(
        None,
        description='Client as it appears in the latest container version since the last workspace synchronization operation. If no client is present, that means the client was deleted in the latest container version.',
    )


class RevertTemplateResponse(BaseModel):
    template: Optional[CustomTemplate] = Field(
        None,
        description='Template as it appears in the latest container version since the last workspace synchronization operation. If no template is present, that means the template was deleted in the latest container version.',
    )


class Tag(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    blockingRuleId: Optional[List[str]] = Field(
        None,
        description='Blocking rule IDs. If any of the listed rules evaluate to true, the tag will not fire. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    blockingTriggerId: Optional[List[str]] = Field(
        None,
        description='Blocking trigger IDs. If any of the listed triggers evaluate to true, the tag will not fire. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    consentSettings: Optional[TagConsentSetting] = Field(
        None,
        description='Consent settings of a tag. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Tag as computed at storage time. This value is recomputed whenever the tag is modified.',
    )
    firingRuleId: Optional[List[str]] = Field(
        None,
        description='Firing rule IDs. A tag will fire when any of the listed rules are true and all of its blockingRuleIds (if any specified) are false. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    firingTriggerId: Optional[List[str]] = Field(
        None,
        description='Firing trigger IDs. A tag will fire when any of the listed triggers are true and all of its blockingTriggerIds (if any specified) are false. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    liveOnly: Optional[bool] = Field(
        None,
        description='If set to true, this tag will only fire in the live environment (e.g. not in preview or debug mode). @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    monitoringMetadata: Optional[Parameter] = Field(
        None,
        description='A map of key-value pairs of tag metadata to be included in the event data for tag monitoring. Notes: - This parameter must be type MAP. - Each parameter in the map are type TEMPLATE, however cannot contain variable references. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    monitoringMetadataTagNameKey: Optional[str] = Field(
        None,
        description='If non-empty, then the tag display name will be included in the monitoring metadata map using the key specified. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    name: Optional[str] = Field(
        None,
        description='Tag display name. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    notes: Optional[str] = Field(
        None,
        description='User notes on how to apply this tag in the container. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    parameter: Optional[List[Parameter]] = Field(
        None,
        description="The tag's parameters. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update",
    )
    parentFolderId: Optional[str] = Field(None, description='Parent folder id.')
    path: Optional[str] = Field(None, description="GTM Tag's API relative path.")
    paused: Optional[bool] = Field(
        None,
        description='Indicates whether the tag is paused, which prevents the tag from firing. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    priority: Optional[Parameter] = Field(
        None,
        description="User defined numeric priority of the tag. Tags are fired asynchronously in order of priority. Tags with higher numeric value fire first. A tag's priority can be a positive or negative value. The default value is 0. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update",
    )
    scheduleEndMs: Optional[str] = Field(
        None,
        description='The end timestamp in milliseconds to schedule a tag. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    scheduleStartMs: Optional[str] = Field(
        None,
        description='The start timestamp in milliseconds to schedule a tag. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    setupTag: Optional[List[SetupTag]] = Field(
        None, description='The list of setup tags. Currently we only allow one.'
    )
    tagFiringOption: Optional[TagFiringOption] = Field(
        None, description='Option to fire this tag.'
    )
    tagId: Optional[str] = Field(
        None, description='The Tag ID uniquely identifies the GTM Tag.'
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    teardownTag: Optional[List[TeardownTag]] = Field(
        None, description='The list of teardown tags. Currently we only allow one.'
    )
    type: Optional[str] = Field(
        None,
        description='GTM Tag Type. @mutable tagmanager.accounts.containers.workspaces.tags.create @mutable tagmanager.accounts.containers.workspaces.tags.update',
    )
    workspaceId: Optional[str] = Field(None, description='GTM Workspace ID.')


class Trigger(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    autoEventFilter: Optional[List[Condition]] = Field(
        None,
        description='Used in the case of auto event tracking. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    checkValidation: Optional[Parameter] = Field(
        None,
        description='Whether or not we should only fire tags if the form submit or link click event is not cancelled by some other event handler (e.g. because of validation). Only valid for Form Submission and Link Click triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    continuousTimeMinMilliseconds: Optional[Parameter] = Field(
        None,
        description='A visibility trigger minimum continuous visible time (in milliseconds). Only valid for AMP Visibility trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    customEventFilter: Optional[List[Condition]] = Field(
        None,
        description='Used in the case of custom event, which is fired iff all Conditions are true. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    eventName: Optional[Parameter] = Field(
        None,
        description='Name of the GTM event that is fired. Only valid for Timer triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    filter: Optional[List[Condition]] = Field(
        None,
        description='The trigger will only fire iff all Conditions are true. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Trigger as computed at storage time. This value is recomputed whenever the trigger is modified.',
    )
    horizontalScrollPercentageList: Optional[Parameter] = Field(
        None,
        description='List of integer percentage values for scroll triggers. The trigger will fire when each percentage is reached when the view is scrolled horizontally. Only valid for AMP scroll triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    interval: Optional[Parameter] = Field(
        None,
        description='Time between triggering recurring Timer Events (in milliseconds). Only valid for Timer triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    intervalSeconds: Optional[Parameter] = Field(
        None,
        description='Time between Timer Events to fire (in seconds). Only valid for AMP Timer trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    limit: Optional[Parameter] = Field(
        None,
        description='Limit of the number of GTM events this Timer Trigger will fire. If no limit is set, we will continue to fire GTM events until the user leaves the page. Only valid for Timer triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    maxTimerLengthSeconds: Optional[Parameter] = Field(
        None,
        description='Max time to fire Timer Events (in seconds). Only valid for AMP Timer trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    name: Optional[str] = Field(
        None,
        description='Trigger display name. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    notes: Optional[str] = Field(
        None,
        description='User notes on how to apply this trigger in the container. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    parameter: Optional[List[Parameter]] = Field(
        None,
        description='Additional parameters. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    parentFolderId: Optional[str] = Field(None, description='Parent folder id.')
    path: Optional[str] = Field(None, description="GTM Trigger's API relative path.")
    selector: Optional[Parameter] = Field(
        None,
        description='A click trigger CSS selector (i.e. "a", "button" etc.). Only valid for AMP Click trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    totalTimeMinMilliseconds: Optional[Parameter] = Field(
        None,
        description='A visibility trigger minimum total visible time (in milliseconds). Only valid for AMP Visibility trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    triggerId: Optional[str] = Field(
        None, description='The Trigger ID uniquely identifies the GTM Trigger.'
    )
    type: Optional[Type4] = Field(
        None,
        description='Defines the data layer event that causes this trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    uniqueTriggerId: Optional[Parameter] = Field(
        None,
        description="Globally unique id of the trigger that auto-generates this (a Form Submit, Link Click or Timer listener) if any. Used to make incompatible auto-events work together with trigger filtering based on trigger ids. This value is populated during output generation since the tags implied by triggers don't exist until then. Only valid for Form Submit, Link Click and Timer triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update",
    )
    verticalScrollPercentageList: Optional[Parameter] = Field(
        None,
        description='List of integer percentage values for scroll triggers. The trigger will fire when each percentage is reached when the view is scrolled vertically. Only valid for AMP scroll triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    visibilitySelector: Optional[Parameter] = Field(
        None,
        description='A visibility trigger CSS selector (i.e. "#id"). Only valid for AMP Visibility trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    visiblePercentageMax: Optional[Parameter] = Field(
        None,
        description='A visibility trigger maximum percent visibility. Only valid for AMP Visibility trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    visiblePercentageMin: Optional[Parameter] = Field(
        None,
        description='A visibility trigger minimum percent visibility. Only valid for AMP Visibility trigger. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    waitForTags: Optional[Parameter] = Field(
        None,
        description='Whether or not we should delay the form submissions or link opening until all of the tags have fired (by preventing the default action and later simulating the default action). Only valid for Form Submission and Link Click triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update',
    )
    waitForTagsTimeout: Optional[Parameter] = Field(
        None,
        description="How long to wait (in milliseconds) for tags to fire when 'waits_for_tags' above evaluates to true. Only valid for Form Submission and Link Click triggers. @mutable tagmanager.accounts.containers.workspaces.triggers.create @mutable tagmanager.accounts.containers.workspaces.triggers.update",
    )
    workspaceId: Optional[str] = Field(None, description='GTM Workspace ID.')


class Variable(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    disablingTriggerId: Optional[List[str]] = Field(
        None,
        description='For mobile containers only: A list of trigger IDs for disabling conditional variables; the variable is enabled if one of the enabling trigger is true while all the disabling trigger are false. Treated as an unordered set. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update',
    )
    enablingTriggerId: Optional[List[str]] = Field(
        None,
        description='For mobile containers only: A list of trigger IDs for enabling conditional variables; the variable is enabled if one of the enabling triggers is true while all the disabling triggers are false. Treated as an unordered set. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update',
    )
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Variable as computed at storage time. This value is recomputed whenever the variable is modified.',
    )
    formatValue: Optional[VariableFormatValue] = Field(
        None, description='Option to convert a variable value to other value.'
    )
    name: Optional[str] = Field(
        None,
        description='Variable display name. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update',
    )
    notes: Optional[str] = Field(
        None,
        description='User notes on how to apply this variable in the container. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update',
    )
    parameter: Optional[List[Parameter]] = Field(
        None,
        description="The variable's parameters. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update",
    )
    parentFolderId: Optional[str] = Field(None, description='Parent folder id.')
    path: Optional[str] = Field(None, description="GTM Variable's API relative path.")
    scheduleEndMs: Optional[str] = Field(
        None,
        description='The end timestamp in milliseconds to schedule a variable. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update',
    )
    scheduleStartMs: Optional[str] = Field(
        None,
        description='The start timestamp in milliseconds to schedule a variable. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update',
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    type: Optional[str] = Field(
        None,
        description='GTM Variable Type. @mutable tagmanager.accounts.containers.workspaces.variables.create @mutable tagmanager.accounts.containers.workspaces.variables.update',
    )
    variableId: Optional[str] = Field(
        None, description='The Variable ID uniquely identifies the GTM Variable.'
    )
    workspaceId: Optional[str] = Field(None, description='GTM Workspace ID.')


class ZoneBoundary(BaseModel):
    condition: Optional[List[Condition]] = Field(
        None, description='The conditions that, when conjoined, make up the boundary.'
    )
    customEvaluationTriggerId: Optional[List[str]] = Field(
        None,
        description='Custom evaluation trigger IDs. A zone will evaluate its boundary conditions when any of the listed triggers are true.',
    )


class Entity(BaseModel):
    changeStatus: Optional[ChangeStatus] = Field(
        None, description='Represents how the entity has been changed in the workspace.'
    )
    client: Optional[Client] = Field(
        None, description='The client being represented by the entity.'
    )
    folder: Optional[Folder] = Field(
        None, description='The folder being represented by the entity.'
    )
    tag: Optional[Tag] = Field(
        None, description='The tag being represented by the entity.'
    )
    trigger: Optional[Trigger] = Field(
        None, description='The trigger being represented by the entity.'
    )
    variable: Optional[Variable] = Field(
        None, description='The variable being represented by the entity.'
    )


class FolderEntities(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    tag: Optional[List[Tag]] = Field(
        None, description='The list of tags inside the folder.'
    )
    trigger: Optional[List[Trigger]] = Field(
        None, description='The list of triggers inside the folder.'
    )
    variable: Optional[List[Variable]] = Field(
        None, description='The list of variables inside the folder.'
    )


class ListTagsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    tag: Optional[List[Tag]] = Field(
        None, description='All GTM Tags of a GTM Container.'
    )


class ListTriggersResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    trigger: Optional[List[Trigger]] = Field(
        None, description='All GTM Triggers of a GTM Container.'
    )


class ListVariablesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    variable: Optional[List[Variable]] = Field(
        None, description='All GTM Variables of a GTM Container.'
    )


class MergeConflict(BaseModel):
    entityInBaseVersion: Optional[Entity] = Field(
        None,
        description='The base version entity (since the latest sync operation) that has conflicting changes compared to the workspace. If this field is missing, it means the workspace entity is deleted from the base version.',
    )
    entityInWorkspace: Optional[Entity] = Field(
        None,
        description='The workspace entity that has conflicting changes compared to the base version. If an entity is deleted in a workspace, it will still appear with a deleted change status.',
    )


class RevertTagResponse(BaseModel):
    tag: Optional[Tag] = Field(
        None,
        description='Tag as it appears in the latest container version since the last workspace synchronization operation. If no tag is present, that means the tag was deleted in the latest container version.',
    )


class RevertTriggerResponse(BaseModel):
    trigger: Optional[Trigger] = Field(
        None,
        description='Trigger as it appears in the latest container version since the last workspace synchronization operation. If no trigger is present, that means the trigger was deleted in the latest container version.',
    )


class RevertVariableResponse(BaseModel):
    variable: Optional[Variable] = Field(
        None,
        description='Variable as it appears in the latest container version since the last workspace synchronization operation. If no variable is present, that means the variable was deleted in the latest container version.',
    )


class SyncWorkspaceResponse(BaseModel):
    mergeConflict: Optional[List[MergeConflict]] = Field(
        None,
        description='The merge conflict after sync. If this field is not empty, the sync is still treated as successful. But a version cannot be created until all conflicts are resolved.',
    )
    syncStatus: Optional[SyncStatus] = Field(
        None,
        description='Indicates whether synchronization caused a merge conflict or sync error.',
    )


class Zone(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    boundary: Optional[ZoneBoundary] = Field(None, description="This Zone's boundary.")
    childContainer: Optional[List[ZoneChildContainer]] = Field(
        None, description='Containers that are children of this Zone.'
    )
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Zone as computed at storage time. This value is recomputed whenever the zone is modified.',
    )
    name: Optional[str] = Field(None, description='Zone display name.')
    notes: Optional[str] = Field(
        None, description='User notes on how to apply this zone in the container.'
    )
    path: Optional[str] = Field(None, description="GTM Zone's API relative path.")
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    typeRestriction: Optional[ZoneTypeRestriction] = Field(
        None, description="This Zone's type restrictions."
    )
    workspaceId: Optional[str] = Field(None, description='GTM Workspace ID.')
    zoneId: Optional[str] = Field(
        None, description='The Zone ID uniquely identifies the GTM Zone.'
    )


class ContainerVersion(BaseModel):
    accountId: Optional[str] = Field(None, description='GTM Account ID.')
    builtInVariable: Optional[List[BuiltInVariable]] = Field(
        None,
        description='The built-in variables in the container that this version was taken from.',
    )
    client: Optional[List[Client]] = Field(
        None,
        description='The clients in the container that this version was taken from.',
    )
    container: Optional[Container] = Field(
        None, description='The container that this version was taken from.'
    )
    containerId: Optional[str] = Field(None, description='GTM Container ID.')
    containerVersionId: Optional[str] = Field(
        None,
        description='The Container Version ID uniquely identifies the GTM Container Version.',
    )
    customTemplate: Optional[List[CustomTemplate]] = Field(
        None,
        description='The custom templates in the container that this version was taken from.',
    )
    deleted: Optional[bool] = Field(
        None,
        description='A value of true indicates this container version has been deleted.',
    )
    description: Optional[str] = Field(
        None,
        description='Container version description. @mutable tagmanager.accounts.containers.versions.update',
    )
    fingerprint: Optional[str] = Field(
        None,
        description='The fingerprint of the GTM Container Version as computed at storage time. This value is recomputed whenever the container version is modified.',
    )
    folder: Optional[List[Folder]] = Field(
        None,
        description='The folders in the container that this version was taken from.',
    )
    gtagConfig: Optional[List[GtagConfig]] = Field(
        None,
        description='The Google tag configs in the container that this version was taken from.',
    )
    name: Optional[str] = Field(
        None,
        description='Container version display name. @mutable tagmanager.accounts.containers.versions.update',
    )
    path: Optional[str] = Field(
        None, description="GTM Container Version's API relative path."
    )
    tag: Optional[List[Tag]] = Field(
        None, description='The tags in the container that this version was taken from.'
    )
    tagManagerUrl: Optional[str] = Field(
        None, description='Auto generated link to the tag manager UI'
    )
    trigger: Optional[List[Trigger]] = Field(
        None,
        description='The triggers in the container that this version was taken from.',
    )
    variable: Optional[List[Variable]] = Field(
        None,
        description='The variables in the container that this version was taken from.',
    )
    zone: Optional[List[Zone]] = Field(
        None, description='The zones in the container that this version was taken from.'
    )


class CreateContainerVersionResponse(BaseModel):
    compilerError: Optional[bool] = Field(None, description='Compiler errors or not.')
    containerVersion: Optional[ContainerVersion] = Field(
        None, description='The container version created.'
    )
    newWorkspacePath: Optional[str] = Field(
        None,
        description='Auto generated workspace path created as a result of version creation. This field should only be populated if the created version was not a quick preview.',
    )
    syncStatus: Optional[SyncStatus] = Field(
        None,
        description='Whether version creation failed when syncing the workspace to the latest container version.',
    )


class GetWorkspaceStatusResponse(BaseModel):
    mergeConflict: Optional[List[MergeConflict]] = Field(
        None, description='The merge conflict after sync.'
    )
    workspaceChange: Optional[List[Entity]] = Field(
        None, description='Entities that have been changed in the workspace.'
    )


class ListZonesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='Continuation token for fetching the next page of results.'
    )
    zone: Optional[List[Zone]] = Field(
        None, description='All GTM Zones of a GTM Container.'
    )


class PublishContainerVersionResponse(BaseModel):
    compilerError: Optional[bool] = Field(None, description='Compiler errors or not.')
    containerVersion: Optional[ContainerVersion] = Field(
        None, description='The container version created.'
    )


class QuickPreviewResponse(BaseModel):
    compilerError: Optional[bool] = Field(
        None, description='Were there compiler errors or not.'
    )
    containerVersion: Optional[ContainerVersion] = Field(
        None, description='The quick previewed container version.'
    )
    syncStatus: Optional[SyncStatus] = Field(
        None,
        description='Whether quick previewing failed when syncing the workspace to the latest container version.',
    )


class RevertZoneResponse(BaseModel):
    zone: Optional[Zone] = Field(
        None,
        description='Zone as it appears in the latest container version since the last workspace synchronization operation. If no zone is present, that means the zone was deleted in the latest container version.',
    )


Parameter.model_rebuild()
